name: Schedule Facebook Posts

on:
  schedule:
    - cron: '0 10 * * *'  # Körs kl. 12:00 svensk tid (UTC+2)
    - cron: '0 16 * * *'  # Körs kl. 18:00 svensk tid (UTC+2)
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
      FB_PAGE_ID: ${{ secrets.FB_PAGE_ID }}
      FB_PAGE_ACCESS_TOKEN: ${{ secrets.FB_PAGE_ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install python-dotenv requests python-dateutil

      - name: Run script
        run: python schedule_fb_posts.py
